services:
  postgres:
    image: postgres:14.5
    container_name: community-database
    restart: always
    env_file:
      - ./community/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
  redis:
    image: redis:latest
    container_name: community-redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6381:6379"

  web:
    build: .
    container_name: community-web
    restart: always
    volumes:
      - .:/code
    env_file:
      - ./community/.env
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=community.settings
    depends_on:
      - postgres
      - redis
  celery:
    build: .
    container_name: community-celery
    volumes:
      - .:/code
    env_file:
      - ./community/.env
    depends_on:
      - web
      - postgres
      - redis
    command: ['celery', '-A', 'warehouse', 'worker', '--pool=solo', '--loglevel=info']
volumes:
  postgres_data:
  redis_data: