# Generated by Django 5.1.7 on 2025-03-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='categoty',
            field=models.CharField(choices=[('MB', 'Member'), ('DR', 'Driver')], default='MB', max_length=2),
        ),
    ]
