# Generated by Django 5.1.7 on 2025-03-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_member_categoty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='categoty',
            new_name='category',
        ),
    ]
