# Generated by Django 5.1.7 on 2025-03-31 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0007_rename_categoty_member_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('car', 'Car'), ('bus', 'Bus')], default='bus', max_length=3)),
                ('brand', models.CharField(max_length=120)),
                ('year', models.PositiveSmallIntegerField(default=2025)),
                ('capicity', models.PositiveSmallIntegerField(default=2)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_vehicle', to='employees.profile')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_place', models.CharField(max_length=120)),
                ('to_place', models.CharField(max_length=120)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=10, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_booking', to='booking.vehicle')),
            ],
            options={
                'ordering': ['-id', '-start_time', 'end_time'],
                'indexes': [models.Index(fields=['start_time'], name='booking_boo_start_t_a7fa93_idx'), models.Index(fields=['-end_time'], name='booking_boo_end_tim_1f20f0_idx')],
            },
        ),
    ]
