# Generated by Django 5.1.7 on 2025-03-27 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_vehicle_year'),
        ('employees', '0007_rename_categoty_member_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_vehicle', to='employees.member'),
        ),
    ]
