# Generated by Django 5.1.7 on 2025-03-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_vehicle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='from_place',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='to_place',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
