# Generated by Django 5.1.7 on 2025-04-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_order_created_order_date_and_more'),
        ('orders', '0002_order_created_order_updated_alter_order_id'),
    ]

    operations = [
    ]
