# Generated by Django 5.1.7 on 2025-04-02 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='owner',
        ),
    ]
